package com.presentacio;

import javax.swing.*;
import java.awt.*;

/**
 * Created by aleixballetbo on 14/5/17.
 */
public class Encuesta {
    private JFrame frame = new JFrame("Encuesta");
    private JCheckBox checkBox1;
    private JCheckBox checkBox2;
    private JCheckBox checkBox3;
    private JPanel Pregunta1;
    private JLabel Titulo;
    private JLabel opcion1;
    private JLabel opcion2;
    private JLabel opcion3;
    private JPanel Encuesta;

    public Encuesta() {

    }

    public void show() {
        //Encuesta.add(Pregunta1);
        frame.setContentPane(Encuesta);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Encuesta = new JPanel();
        Encuesta.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Título encuesta");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        Encuesta.add(label1, gbc);
        Pregunta1 = new JPanel();
        Pregunta1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridheight = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        Encuesta.add(Pregunta1, gbc);
        opcion3 = new JLabel();
        opcion3.setText("Opción 3");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        Pregunta1.add(opcion3, gbc);
        opcion2 = new JLabel();
        opcion2.setText("Opción 2");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        Pregunta1.add(opcion2, gbc);
        opcion1 = new JLabel();
        opcion1.setText("Opción 1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        Pregunta1.add(opcion1, gbc);
        Titulo = new JLabel();
        Titulo.setText("Título de la pregunta");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        Pregunta1.add(Titulo, gbc);
        checkBox1 = new JCheckBox();
        checkBox1.setText("CheckBox");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        Pregunta1.add(checkBox1, gbc);
        checkBox2 = new JCheckBox();
        checkBox2.setText("CheckBox");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        Pregunta1.add(checkBox2, gbc);
        checkBox3 = new JCheckBox();
        checkBox3.setText("CheckBox");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        Pregunta1.add(checkBox3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Encuesta;
    }
}
