package com.presentacio;

import com.domini.Encuesta;
import com.domini.ExcEncuestaExistente;
import com.domini.ExcFormatoIncorrecto;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;

/**
 * Created by Alejandro on 26/05/2017.
 */
public class VistaClustering {
    private JPanel CPanel;
    private JTable clusterTable;
    private JScrollPane scrollable;

    public VistaClustering(HashMap<Integer, List<String>> clusts) {
        Initialize(clusts);
    }

    public void Initialize(HashMap<Integer, List<String>> clusts) {
        Vector rowData = new Vector();


        String[] columnNames = new String[clusts.size()];
        for (Integer i = 1; i != clusts.size() + 1; ++i) {
            columnNames[i] = i.toString();
            Vector colData = new Vector();
            for (String name : clusts.get(i - 1)) {
                colData.add(name);
            }
            rowData.add(colData);
        }

        Vector columnNamesV = new Vector(Arrays.asList(columnNames));

        JTable table = new JTable(rowData, columnNamesV);
        JFrame f = new JFrame();
        f.setSize(300, 300);
        f.add(new JScrollPane(table));
        f.setVisible(true);
        //clusterTable=new JTable(2,clusts.size());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        CPanel = new JPanel();
        CPanel.setLayout(new BorderLayout(0, 0));
        scrollable = new JScrollPane();
        CPanel.add(scrollable, BorderLayout.CENTER);
        clusterTable = new JTable();
        clusterTable.setFont(new Font("Georgia", clusterTable.getFont().getStyle(), clusterTable.getFont().getSize()));
        scrollable.setViewportView(clusterTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return CPanel;
    }
}
